# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FunctionNames": "linesdk.ipynb",
         "Line": "linesdk.ipynb",
         "LineLambda": "linesdk.ipynb"}

modules = ["linesdk.py"]

doc_url = "https://thanakijwanavit.github.io/linesdk/"

git_url = "https://github.com/thanakijwanavit/linesdk/tree/master/"

def custom_doc_links(name): return None
