# AUTOGENERATED! DO NOT EDIT! File to edit: slack.ipynb (unless otherwise specified).

__all__ = ['SlackBot']

# Cell
from requests import post
import logging

# Cell
class SlackBot:
  def __init__(self,endpoint = 'https://hooks.slack.com/services/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'):
    self.endpoint = endpoint
  def sendMessage(self, message):
    payload = {"text": message}
    self.sSendMessage(self.endpoint, payload)
  @staticmethod
  def sSendMessage(endpoint, payload):
    response = post(url = endpoint, json = payload)
    if response.status_code == 200:
      return response.text
    else:
      logging.error('fail to send message')
      return response.text
