# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PynamoLogger": "PynamoLogger.ipynb"}

modules = ["logger.py"]

doc_url = "https://thanakijwanavit.github.io/pynamoLogger/"

git_url = "https://github.com/thanakijwanavit/pynamologger/tree/master/"

def custom_doc_links(name): return None
